### PR TITLE
Fix layout assets path

### PR DESCRIPTION
**Pull request by ain**

### CODE REVIEW

**Comment by ain** [comment]
@davleh this needs work, which is why it isn't for review.

I'd think `scripts` and `styles` need to move into `dist/`. Is that the `usemin` failure you had in mind?

**Comment by davleh** [comment]
Right, i just removed the usemin part for the moment for my purpose.

**Comment by ain** [comment]
I think it was also commented out historically.

**Comment by ain** [comment]
Closing in favour of #46.

**Pull request closed without merging**
