### PR TITLE
Fix linting errors

### PR DESCRIPTION
**Pull request by davleh**

### CODE REVIEW

**Comment by davleh** [comment]
This is a fix for #35

**Comment by davleh** [comment]
Yes, but this file is not part of the repository. We could add a linter exception, but then tests would not get linted anymore. I would perhaps fix the generator-mocha to meet our conventions?

**Comment by ain** [comment]
1. It's not about Mocha at all
2. JSHint sure already follows the convention
3. All that I meant by meta information were comments in file header for JSHint, e.g. 

    ```js

    /* global expect */ 
    ```

**Comment by ain** [comment]
@beroes could you take this one over from David?

**Comment by beroes** [comment]
@ain I have no idea how to solve this issue.

**Comment by ain** [comment]
@davleh you were right, sorry. It's `generator-mocha` code this `test.js`.

**Comment by davleh** [comment]
So this is mergeable now, right?

**Pull request merged**
